function f = initialization(fcn_ic, ...
                            reference_mass, ...
                            poly_order,...
                            quad_point,quad_weight,...
                            v,...
                            x_center,dx...
                            )
    local_rhs = zeros(poly_order+1,1);
    x_quad = x_center+0.5*quad_point*dx;% 实际网格点
    for k = 0:poly_order
        local_rhs(k+1) = dot(quad_weight,fcn_ic(x_quad,v).*legendre_poly(k,quad_point));
    end
    f = reference_mass\local_rhs;
end